name: Build

on:
  push:
    branches: master

jobs:
  build:
    runs-on: ubuntu-latest
    environment: 
          name: node-env
    steps:
      - uses: actions/checkout@v2

      - name: Hello World
        run: echo Hello, world!
      - name: Send mail
        if: always()
        uses: dawidd6/action-send-mail@v2
        
        with:
          # mail server settings
          server_address: smtp.gmail.com
          server_port: 465
          # user credentials
          username: ${{ secrets.username}}
          password:  ${{ secrets.password }}
          # email subject
          subject: job of has 
          # email body as text
          body: gibberish
          # comma-separated string, send email to
          to: himanshu162pnt@gmail.com
          # from email name
          from: github